/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SseTimeIndexRouteImport } from './routes/sseTime/index'
import { Route as IntervalIndexRouteImport } from './routes/interval/index'
import { Route as CounterIndexRouteImport } from './routes/counter/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'

// Create/Update Routes

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const SseTimeIndexRoute = SseTimeIndexRouteImport.update({
  id: '/sseTime/',
  path: '/sseTime/',
  getParentRoute: () => rootRoute,
} as any)

const IntervalIndexRoute = IntervalIndexRouteImport.update({
  id: '/interval/',
  path: '/interval/',
  getParentRoute: () => rootRoute,
} as any)

const CounterIndexRoute = CounterIndexRouteImport.update({
  id: '/counter/',
  path: '/counter/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/counter/': {
      id: '/counter/'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/interval/': {
      id: '/interval/'
      path: '/interval'
      fullPath: '/interval'
      preLoaderRoute: typeof IntervalIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/sseTime/': {
      id: '/sseTime/'
      path: '/sseTime'
      fullPath: '/sseTime'
      preLoaderRoute: typeof SseTimeIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/counter': typeof CounterIndexRoute
  '/interval': typeof IntervalIndexRoute
  '/sseTime': typeof SseTimeIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/counter': typeof CounterIndexRoute
  '/interval': typeof IntervalIndexRoute
  '/sseTime': typeof SseTimeIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/counter/': typeof CounterIndexRoute
  '/interval/': typeof IntervalIndexRoute
  '/sseTime/': typeof SseTimeIndexRoute
  '/users/': typeof UsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/users/$userId'
    | '/counter'
    | '/interval'
    | '/sseTime'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/users/$userId'
    | '/counter'
    | '/interval'
    | '/sseTime'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/users/$userId'
    | '/counter/'
    | '/interval/'
    | '/sseTime/'
    | '/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  CounterIndexRoute: typeof CounterIndexRoute
  IntervalIndexRoute: typeof IntervalIndexRoute
  SseTimeIndexRoute: typeof SseTimeIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  CounterIndexRoute: CounterIndexRoute,
  IntervalIndexRoute: IntervalIndexRoute,
  SseTimeIndexRoute: SseTimeIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/users/$userId",
        "/counter/",
        "/interval/",
        "/sseTime/",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.tsx"
    },
    "/counter/": {
      "filePath": "counter/index.tsx"
    },
    "/interval/": {
      "filePath": "interval/index.tsx"
    },
    "/sseTime/": {
      "filePath": "sseTime/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
